### ISSUE TITLE
Improvement: Readme

### ISSUE THREAD

**Issue by mthqwork** [abalesluke/PHP_SUS#1]
First, it's a good project, i like it. Thanks!

Readme could be improved, for example to let newcomers know that you need to redirect /z/ to index.php?code=$1.

Also it'd be great to explain the obfuscated js, found at the end of the dashboard.php.

**Comment by abalesluke** [comment]
Thank you so much. I really appreciate your suggestion and correction. I replaced the obfuscated JS with a non-obfuscated one, and I will be fixing the ReadMe.md the way you recommend. 💖💗
